package com.archipin.ludiutils.domain.enums;

import lombok.AllArgsConstructor;

@AllArgsConstructor
public enum IndexableType {
    None,
    Minion,
    MinionSpawnPoint,
    ConstructionBuilding,
    ConstructionBuildingBoard,
    ConstructionBuildingGrid,
    Food,
    Player,
    Npc,
    NpcProxy,
    Building,
    CookingTool,
    TrayTable,
    PackingTable,
    WasteBin,
    Dispenser,
    CommonObject,
    FieldItem,
    Logging_Select,
    Logging_Cut,
    Logging_Item,
    IngredientBox,
    Cart,
    PickableObject,
    Insect,
    Repairable,
    SuspectObject,
    Tree,
    RestaurantObject,
    Pet,
    Diggable,
    Fish,
    NPC_EnterRestaurantDummy,
    LudiPowerTarget,
    TreasureBox,
    Strokable,
    Animal,
    AnimalSpawnPoint,
    Dice,
    LockedObject,
    UnlockedObject,
    Structure,
    ZoneGate,
    TreasureBoxBubble,
    VendingMachine,
    TakableObject,
    Mining,
    StructureChange,
    LudiMachine,
    LudiGameStation,
    Simple,
    Gather,
    LudiPack,
    Ranch,
    EnterMyHouse,
    MyHouseDummyObject,
    FishingSpot,
    FishingArea,
    ClockTower,
    GoodsShop,
    WeatherForecast,
    LudiStation,
    ReporterTruck,
    // === jaewook : DynamicSpot용 Indexable 미리 추가
    Flower, // 꽃 FC에 사용하면 됩니다.
    Leaves, // 낙엽 치우기 FC에 사용하면 됩니다.(FC 정확하게는 아직 미정.)
    // ===
    Photopia,
    CottonCandyMaker,
    Camp,
    Interior,
    // For testing simple interact renewal
    Action,
    Dinosaur,
    Chair,
    LudiTree,
    Max,
}
